### ISSUE TITLE
Controllo della struttura sez B

### ISSUE THREAD

**Issue by luben5691** [RoundaboutTeam/Documentazione#143]
Ho corretto la struttura della sezione B e impostato due grafici di come verrebbe Gulpease e Flasch.
Apro una issue per chiederti che ne pensi.

**Comment by nicolettafbr** [comment]
> Ho corretto la struttura della sezione B e impostato due grafici di come verrebbe Gulpease e Flasch.
> Apro una issue per chiederti che ne pensi.

La forma mi sembra ottima! Direi di continuare così.

**Comment by nicolettafbr** [comment]
Ti segnalo solo un'incorrettezza grammaticale: nella sezione B.1.2.1 nel sottotitolo scrivi 'Forma di Flash' quando la forma corretta è 'Flesch' (come hai scritto poi nel paragrafo)
